### ISSUE TITLE
Please point to Casbin.NET instead of Casbin, and add badges

### ISSUE THREAD

**Issue by hsluoyz** [Sbou/Casbin.NET-Redis-Watcher#1]
Thanks for the contribution to the community ! I have added your watcher to official site: https://github.com/casbin/casbin-website/commit/f7e2a03d4abfdff20696b20d0cf5d13b3f5cd38a

Can you add badges like: https://github.com/casbin/Casbin.NET

![image](https://user-images.githubusercontent.com/3787410/69388459-dc482500-0d03-11ea-9586-eeb66cbef9d6.png)

**Comment by Sbou** [comment]
Done
