### ISSUE TITLE
Release date for redis watcher compatible with version Casbin.NET v2

### ISSUE THREAD

**Issue by homorozeanu** [Sbou/Casbin.NET-Redis-Watcher#7]
Hi Team,

we would like to build our AuthZ custom solution based on Casbin.NET version 2. 
Do you have any roadmap or additional information about the release date of the redis watcher compatible with Casbin.NET version 2?

Best regards
George

**Comment by hsluoyz** [comment]
@Sbou

**Comment by Sbou** [comment]
Hello,
I’m off but I will work on it after the 22/08.

**Comment by Sbou** [comment]
Release 2.0.0 is available !!
